version: '3'

services:
  database:
    image: mysql:5.7
    container_name: MY-DB-CONTAINER
    restart: always
    expose:
      - "3306"
    volumes:
      - ./mysql_dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:4.9.6
    container_name: MY-WP-CONTAINER
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    depends_on:
      - database

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    container_name: MY-PA-CONTAINER
    ports:
      - "8181:80"
    restart: always
    environment:
      PMA_PORT: 3306
      PMA_HOST: database
    depends_on:
      - database
